
stages:
  - build
  - release

before_script:
  - mkdir -p _ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/_ccache

cache:
  paths:
    - _ccache/

build:
  image: archlinux/base
  stage: build
  script:
   - pacman -Sy
   - pacman -S --noconfirm gtk3 vala cmake git base-devel ninja libxkbcommon-x11 libxcb alsa-lib libcanberra libgweather libx11 libgtop
   - git clone https://gitlab.com/vala-panel-project/cmake-vala.git
   - cd cmake-vala && cmake . -DCMAKE_INSTALL_PREFIX=/usr -GNinja && ninja install && cd .. && rm -rf cmake-vala
   - mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -GNinja
   - ninja
   - ninja install
   - ninja dist
  artifacts:
    paths:
    - "build/vala-panel*.tar.xz"
    expire_in: 1 week

release-main:
  image: archlinux/base
  stage: release
  script:
    - pacman -Sy
    - pacman -S --noconfirm python3 python-pip
    - pip3 install gitlab_release
    - python3 -m gitlab_release ${PRIVATE_TOKEN} build/vala-panel*.tar.xz
  only:
    - tags
